export const SELECT_GRID_ITEM = 'SELECT_GRID_ITEM';
export const SET_INITIAL_PLAYERS_STATE = 'SET_INITIAL_PLAYERS_STATE';
export const TOGGLE_KEYBOARD = 'TOGGLE_KEYBOARD';
export const RESET_GRID = 'RESET_GRID';
