export const SELECT_GRID_ITEM = 'SELECT_GRID_ITEM';
export const TOGGLE_KEYBOARD = 'TOGGLE_KEYBOARD';
export const UPDATE_PLAYER_RANK = 'UPDATE_PLAYER_RANK';
export const UPDATE_PLAYER_SUIT = 'UPDATE_PLAYER_SUIT';
export const RESET_GRID = 'RESET_GRID';
